<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>DiscordVideoCompressor</RootNamespace>
    <AssemblyName>DiscordVideoCompressor</AssemblyName>
    <ApplicationIcon>pk_icon.ico</ApplicationIcon>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Main.cs" />
    <Compile Remove="Main.Designer.cs" />
    <EmbeddedResource Remove="Main.resx" />

    <Compile Update="Form1_BR.Designer.cs">
      <DependentUpon>Form1_BR.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Form1_BR.resx">
      <DependentUpon>Form1_BR.cs</DependentUpon>
    </EmbeddedResource>

    <Compile Update="Resources\\Strings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources\\Strings.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Resources\\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>

    <EmbeddedResource Update="Resources\\Strings.ru.resx" />

    <EmbeddedResource Update="Properties\\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <Compile Update="Properties\\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Properties\\Resources.resx</DependentUpon>
    </Compile>

    <None Update="Properties\\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="Properties\\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Properties\\Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
</Project>
