//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordVideoCompressor.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordVideoCompressor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The target size is too small for this video..
        /// </summary>
        internal static string BitrateErrorMessage {
            get {
                return ResourceManager.GetString("BitrateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a media file.
        /// </summary>
        internal static string ChooseMediaFileButtonText {
            get {
                return ResourceManager.GetString("ChooseMediaFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The conversion was canceled..
        /// </summary>
        internal static string ConversionCanceledMessage {
            get {
                return ResourceManager.GetString("ConversionCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conversion error: .
        /// </summary>
        internal static string ConversionErrorMessage {
            get {
                return ResourceManager.GetString("ConversionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conversion completed: .
        /// </summary>
        internal static string ConversionSuccessMessage {
            get {
                return ResourceManager.GetString("ConversionSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert.
        /// </summary>
        internal static string ConvertationButtonText {
            get {
                return ResourceManager.GetString("ConvertationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom size (MB):.
        /// </summary>
        internal static string CustomSizeLabel {
            get {
                return ResourceManager.GetString("CustomSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to determine the video duration. ffmpeg output:.
        /// </summary>
        internal static string DurationErrorMessage {
            get {
                return ResourceManager.GetString("DurationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a valid size in MB..
        /// </summary>
        internal static string EnterValidSizeMessage {
            get {
                return ResourceManager.GetString("EnterValidSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ffmpeg Extraction failed..
        /// </summary>
        internal static string FfmpegExtractionErrorMessage {
            get {
                return ResourceManager.GetString("FfmpegExtractionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to achieve the desired file size..
        /// </summary>
        internal static string FileConversionErrorMessage {
            get {
                return ResourceManager.GetString("FileConversionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file does not exist..
        /// </summary>
        internal static string FileNotExistError {
            get {
                return ResourceManager.GetString("FileNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Force stop.
        /// </summary>
        internal static string ForceStopButtonText {
            get {
                return ResourceManager.GetString("ForceStopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discord 9 MB.
        /// </summary>
        internal static string DiscordPresetText {
            get {
                return ResourceManager.GetString("DiscordPresetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Max Size (MB).
        /// </summary>
        internal static string CustomMaxSizeText {
            get {
                return ResourceManager.GetString("CustomMaxSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brainrot Edition.
        /// </summary>
        internal static string BrainrotEditionText {
            get {
                return ResourceManager.GetString("BrainrotEditionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smooth speed effect.
        /// </summary>
        internal static string BrainrotSpeedEffectText {
            get {
                return ResourceManager.GetString("BrainrotSpeedEffectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Datamosh effect.
        /// </summary>
        internal static string BrainrotDatamoshEffectText {
            get {
                return ResourceManager.GetString("BrainrotDatamoshEffectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glitch.
        /// </summary>
        internal static string BrainrotGlitchEffectText {
            get {
                return ResourceManager.GetString("BrainrotGlitchEffectText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Stage:.
        /// </summary>
        internal static string ProgressStageLabelText {
            get {
                return ResourceManager.GetString("ProgressStageLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Idle.
        /// </summary>
        internal static string ProgressStageIdleText {
            get {
                return ResourceManager.GetString("ProgressStageIdleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing.
        /// </summary>
        internal static string ProgressStagePrepare {
            get {
                return ResourceManager.GetString("ProgressStagePrepare", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Glitch pass.
        /// </summary>
        internal static string ProgressStageGlitch {
            get {
                return ResourceManager.GetString("ProgressStageGlitch", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed pass.
        /// </summary>
        internal static string ProgressStageSpeed {
            get {
                return ResourceManager.GetString("ProgressStageSpeed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Pass 1/2.
        /// </summary>
        internal static string ProgressStagePass1 {
            get {
                return ResourceManager.GetString("ProgressStagePass1", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Pass 2/2.
        /// </summary>
        internal static string ProgressStagePass2 {
            get {
                return ResourceManager.GetString("ProgressStagePass2", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Datamosh encode.
        /// </summary>
        internal static string ProgressStageDatamoshEncode {
            get {
                return ResourceManager.GetString("ProgressStageDatamoshEncode", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Datamosh transform.
        /// </summary>
        internal static string ProgressStageDatamoshTransform {
            get {
                return ResourceManager.GetString("ProgressStageDatamoshTransform", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Datamosh remux.
        /// </summary>
        internal static string ProgressStageDatamoshRemux {
            get {
                return ResourceManager.GetString("ProgressStageDatamoshRemux", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на ETA.
        /// </summary>
        internal static string ProgressEtaLabelText {
            get {
                return ResourceManager.GetString("ProgressEtaLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed.
        /// </summary>
        internal static string ProgressSpeedLabelText {
            get {
                return ResourceManager.GetString("ProgressSpeedLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на --:-- / --:--.
        /// </summary>
        internal static string ProgressTimeIdleText {
            get {
                return ResourceManager.GetString("ProgressTimeIdleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Jump length (s).
        /// </summary>
        internal static string GlitchJumpLengthLabelText {
            get {
                return ResourceManager.GetString("GlitchJumpLengthLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Chance (%).
        /// </summary>
        internal static string GlitchChanceLabelText {
            get {
                return ResourceManager.GetString("GlitchChanceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resolution.
        /// </summary>
        internal static string ResolutionLabelText {
            get {
                return ResourceManager.GetString("ResolutionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sample Rate.
        /// </summary>
        internal static string SampleRateLabelText {
            get {
                return ResourceManager.GetString("SampleRateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bit Depth.
        /// </summary>
        internal static string BitDepthLabelText {
            get {
                return ResourceManager.GetString("BitDepthLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FPS.
        /// </summary>
        internal static string FpsLabelText {
            get {
                return ResourceManager.GetString("FpsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid file extension..
        /// </summary>
        internal static string InvalidFileFormatMessage {
            get {
                return ResourceManager.GetString("InvalidFileFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No file.
        /// </summary>
        internal static string NoFileSelectedText {
            get {
                return ResourceManager.GetString("NoFileSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected file: .
        /// </summary>
        internal static string SelectedFileLabelText {
            get {
                return ResourceManager.GetString("SelectedFileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose a media file..
        /// </summary>
        internal static string SelectMediaFileMessage {
            get {
                return ResourceManager.GetString("SelectMediaFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select an output format..
        /// </summary>
        internal static string SelectOutputFormatMessage {
            get {
                return ResourceManager.GetString("SelectOutputFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Datamosh works only with MP4 output. Choose MP4 or use Glitch..
        /// </summary>
        internal static string DatamoshMp4OnlyMessage {
            get {
                return ResourceManager.GetString("DatamoshMp4OnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Datamosh cannot be combined with the speed effect..
        /// </summary>
        internal static string DatamoshSpeedConflictMessage {
            get {
                return ResourceManager.GetString("DatamoshSpeedConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select only one of Datamosh or Glitch..
        /// </summary>
        internal static string DatamoshMutualExclusiveMessage {
            get {
                return ResourceManager.GetString("DatamoshMutualExclusiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Datamosh output has no audio. Log saved at: .
        /// </summary>
        internal static string DatamoshAudioMissingMessage {
            get {
                return ResourceManager.GetString("DatamoshAudioMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select a size option..
        /// </summary>
        internal static string SelectSizeOptionMessage {
            get {
                return ResourceManager.GetString("SelectSizeOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size option.
        /// </summary>
        internal static string SizeOptionLabel {
            get {
                return ResourceManager.GetString("SizeOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error converting time. Debug: Check the time string format..
        /// </summary>
        internal static string TimeConversionErrorMessage {
            get {
                return ResourceManager.GetString("TimeConversionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The video duration is incorrect..
        /// </summary>
        internal static string VideoDurationErrorMessage {
            get {
                return ResourceManager.GetString("VideoDurationErrorMessage", resourceCulture);
            }
        }
    }
}
